all:
	g++ Lagrange.cpp -o Lagrange -std=c++17
	g++ Newton.cpp -o Newton -std=c++17
	g++ ATAATb.cpp -o ATAATb -std=c++17
	g++ QR.cpp -o QR -std=c++17
	g++ Mixture.cpp -o Mixture -std=c++17
	g++ Optimization.cpp -o Optimization -std=c++17
	